export const sdgGoals = [
  { number: 1, title: "No Poverty", value: "1", label: "No Poverty" },
  { number: 2, title: "Zero Hunger", value: "2", label: "Zero Hunger" },
  { number: 3, title: "Good Health and Well-being", value: "3", label: "Good Health and Well-being" },
  { number: 4, title: "Quality Education", value: "4", label: "Quality Education" },
  { number: 5, title: "Gender Equality", value: "5", label: "Gender Equality" },
  { number: 6, title: "Clean Water and Sanitation", value: "6", label: "Clean Water and Sanitation" },
  { number: 7, title: "Affordable and Clean Energy", value: "7", label: "Affordable and Clean Energy" },
  { number: 8, title: "Decent Work and Economic Growth", value: "8", label: "Decent Work and Economic Growth" },
  { number: 9, title: "Industry, Innovation and Infrastructure", value: "9", label: "Industry, Innovation and Infrastructure" },
  { number: 10, title: "Reduced Inequalities", value: "10", label: "Reduced Inequalities" },
  { number: 11, title: "Sustainable Cities and Communities", value: "11", label: "Sustainable Cities and Communities" },
  { number: 12, title: "Responsible Consumption and Production", value: "12", label: "Responsible Consumption and Production" },
  { number: 13, title: "Climate Action", value: "13", label: "Climate Action" },
  { number: 14, title: "Life Below Water", value: "14", label: "Life Below Water" },
  { number: 15, title: "Life on Land", value: "15", label: "Life on Land" },
  { number: 16, title: "Peace, Justice and Strong Institutions", value: "16", label: "Peace, Justice and Strong Institutions" },
  { number: 17, title: "Partnerships for the Goals", value: "17", label: "Partnerships for the Goals" }
];

export const africaCountries = [
  { name: 'Algeria', code: 'DZ' },
  { name: 'Angola', code: 'AO' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cabo Verde', code: 'CV' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, Democratic Republic of the', code: 'CD' },
  { name: 'Cote d\'Ivoire', code: 'CI' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Egypt', code: 'EG' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Eswatini', code: 'SZ' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libya', code: 'LY' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Mali', code: 'ML' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Sudan', code: 'SS' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' }
];
