project_id = "ptfrzwsivtetvmdotfui"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54321"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
anonymous_users_enabled = false

[db]
port = 54322

[functions]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.organization-management]
verify_jwt = false

[edge_runtime]
policy = "oneshot"