import { useState } from "react";
import { escapeHtml } from "@/lib/escapeHtml";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Globe } from "lucide-react";
import { toast } from "sonner";

const DONOR_TEMPLATES = [
  { value: "world_bank", label: "World Bank ICR", description: "Implementation Completion Report format" },
  { value: "undp", label: "UNDP ROAR", description: "Results-Oriented Annual Report" },
  { value: "afdb", label: "AfDB PCR", description: "Project Completion Report" },
  { value: "gef", label: "GEF PIR", description: "Project Implementation Review" },
  { value: "generic", label: "Generic Donor Report", description: "Standard development report format" },
];

interface DonorReportExportProps {
  report: any;
  milestones?: any[];
  budgets?: any[];
  indicators?: any[];
}

export default function DonorReportExport({ report, milestones = [], budgets = [], indicators = [] }: DonorReportExportProps) {
  const [template, setTemplate] = useState("generic");
  const [generating, setGenerating] = useState(false);

  const generateReport = () => {
    setGenerating(true);
    try {
      const tmpl = DONOR_TEMPLATES.find(t => t.value === template);
      const now = new Date().toLocaleDateString();

      const milestoneRows = milestones.map(m =>
        `<tr><td>${escapeHtml(m.title)}</td><td>${escapeHtml(m.target_date) || '-'}</td><td>${m.completed ? '✅ Complete' : '⏳ Pending'}</td></tr>`
      ).join('');

      const budgetRows = budgets.map(b =>
        `<tr><td>${escapeHtml(b.source) || '-'}</td><td>${escapeHtml(b.currency)} ${(b.allocated || 0).toLocaleString()}</td><td>${escapeHtml(b.currency)} ${(b.spent || 0).toLocaleString()}</td><td>${b.allocated > 0 ? Math.round((b.spent / b.allocated) * 100) : 0}%</td></tr>`
      ).join('');

      const indicatorRows = indicators.map(i =>
        `<tr><td>${escapeHtml(i.name)}</td><td>${escapeHtml(i.baseline) || '-'}</td><td>${escapeHtml(i.current_value) || '-'}</td><td>${escapeHtml(i.target_value) || '-'}</td><td>${escapeHtml(i.unit) || '-'}</td></tr>`
      ).join('');

      const html = `<!DOCTYPE html>
<html>
<head>
  <title>${escapeHtml(tmpl?.label)} - ${escapeHtml(report.title)}</title>
  <style>
    body { font-family: 'Times New Roman', serif; margin: 50px; color: #333; line-height: 1.6; }
    h1 { text-align: center; border-bottom: 3px double #333; padding-bottom: 10px; }
    h2 { color: #1a5276; border-bottom: 1px solid #1a5276; padding-bottom: 5px; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0 20px; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background: #f0f4f8; font-weight: bold; }
    .meta { display: flex; justify-content: space-between; color: #666; font-size: 14px; margin: 20px 0; }
    .section { margin: 20px 0; }
    .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; background: #e8f4fd; color: #1a5276; font-size: 12px; margin: 2px; }
    @media print { body { margin: 30px; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(tmpl?.label) || 'Donor Report'}</h1>
  <div class="meta">
    <span>Project: ${escapeHtml(report.title)}</span>
    <span>Generated: ${now}</span>
  </div>

  <h2>1. Project Overview</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Project Title</td><td>${escapeHtml(report.title)}</td></tr>
    <tr><td>Description</td><td>${escapeHtml(report.description) || '-'}</td></tr>
    <tr><td>Location</td><td>${escapeHtml(report.location) || '-'}</td></tr>
    <tr><td>SDG Alignment</td><td>SDG ${escapeHtml(String(report.sdg_goal))}</td></tr>
    <tr><td>Status</td><td>${escapeHtml(report.project_status) || '-'}</td></tr>
    <tr><td>Beneficiaries</td><td>${report.beneficiaries?.toLocaleString() || '-'}</td></tr>
    <tr><td>Start Date</td><td>${escapeHtml(report.start_date) || '-'}</td></tr>
    <tr><td>End Date</td><td>${escapeHtml(report.end_date) || '-'}</td></tr>
  </table>

  <h2>2. Milestones & Progress</h2>
  ${milestoneRows ? `<table><tr><th>Milestone</th><th>Target Date</th><th>Status</th></tr>${milestoneRows}</table>` : '<p>No milestones recorded.</p>'}

  <h2>3. Budget & Expenditure</h2>
  ${budgetRows ? `<table><tr><th>Source</th><th>Allocated</th><th>Spent</th><th>Utilization</th></tr>${budgetRows}</table>` : '<p>No budget data recorded.</p>'}

  <h2>4. Impact Indicators</h2>
  ${indicatorRows ? `<table><tr><th>Indicator</th><th>Baseline</th><th>Current</th><th>Target</th><th>Unit</th></tr>${indicatorRows}</table>` : '<p>No indicators recorded.</p>'}

  <h2>5. Conclusions & Recommendations</h2>
  <p>This report was auto-generated by DevMapper Earth — Africa's Development Intelligence Platform.</p>
  <p><em>For verification status and citizen feedback, visit the project page on devmapper.africa</em></p>
</body>
</html>`;

      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        // Auto-trigger print dialog
        setTimeout(() => printWindow.print(), 500);
      }
      toast.success(`${tmpl?.label} generated — use Print to save as PDF`);
    } catch {
      toast.error("Failed to generate report");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base flex items-center gap-2">
          <Globe className="h-4 w-4" /> Donor Report Export
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label>Report Template</Label>
          <Select value={template} onValueChange={setTemplate}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>
              {DONOR_TEMPLATES.map(t => (
                <SelectItem key={t.value} value={t.value}>
                  <div className="flex items-center gap-2">
                    <span>{t.label}</span>
                    <span className="text-xs text-muted-foreground">— {t.description}</span>
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="flex flex-wrap gap-1">
          {DONOR_TEMPLATES.map(t => (
            <Badge key={t.value} variant={template === t.value ? "default" : "outline"} className="cursor-pointer" onClick={() => setTemplate(t.value)}>
              {t.label}
            </Badge>
          ))}
        </div>
        <Button onClick={generateReport} disabled={generating} className="w-full">
          <Download className="mr-2 h-4 w-4" />
          {generating ? "Generating..." : "Generate Donor Report"}
        </Button>
      </CardContent>
    </Card>
  );
}
