
-- Seed Country Intelligence data for all 54 African countries
INSERT INTO public.country_intelligence (country_code, country_name, iso2_code, official_languages, currency_code, regional_blocs, stock_exchange_name) VALUES
('DZA', 'Algeria', 'DZ', '["ar","fr"]', 'DZD', '["AU"]', 'Algiers Stock Exchange'),
('AGO', 'Angola', 'AO', '["pt"]', 'AOA', '["AU","SADC"]', 'BODIVA'),
('BEN', 'Benin', 'BJ', '["fr"]', 'XOF', '["AU","ECOWAS"]', 'BRVM'),
('BWA', 'Botswana', 'BW', '["en"]', 'BWP', '["AU","SADC"]', 'BSE'),
('BFA', 'Burkina Faso', 'BF', '["fr"]', 'XOF', '["AU","ECOWAS"]', 'BRVM'),
('BDI', 'Burundi', 'BI', '["fr","rn"]', 'BIF', '["AU","EAC"]', NULL),
('CMR', 'Cameroon', 'CM', '["fr","en"]', 'XAF', '["AU","CEMAC"]', 'DSX'),
('CPV', 'Cape Verde', 'CV', '["pt"]', 'CVE', '["AU","ECOWAS"]', 'BVC'),
('CAF', 'Central African Republic', 'CF', '["fr","sg"]', 'XAF', '["AU","CEMAC"]', NULL),
('TCD', 'Chad', 'TD', '["fr","ar"]', 'XAF', '["AU","CEMAC"]', NULL),
('COM', 'Comoros', 'KM', '["ar","fr"]', 'KMF', '["AU"]', NULL),
('COG', 'Congo', 'CG', '["fr"]', 'XAF', '["AU","CEMAC"]', NULL),
('COD', 'Democratic Republic of Congo', 'CD', '["fr"]', 'CDF', '["AU","SADC"]', NULL),
('CIV', 'Côte d''Ivoire', 'CI', '["fr"]', 'XOF', '["AU","ECOWAS"]', 'BRVM'),
('DJI', 'Djibouti', 'DJ', '["fr","ar"]', 'DJF', '["AU"]', NULL),
('EGY', 'Egypt', 'EG', '["ar"]', 'EGP', '["AU"]', 'EGX'),
('GNQ', 'Equatorial Guinea', 'GQ', '["es","fr","pt"]', 'XAF', '["AU","CEMAC"]', NULL),
('ERI', 'Eritrea', 'ER', '["ti","ar","en"]', 'ERN', '["AU"]', NULL),
('ETH', 'Ethiopia', 'ET', '["am"]', 'ETB', '["AU"]', 'ESX'),
('GAB', 'Gabon', 'GA', '["fr"]', 'XAF', '["AU","CEMAC"]', NULL),
('GMB', 'Gambia', 'GM', '["en"]', 'GMD', '["AU","ECOWAS"]', NULL),
('GHA', 'Ghana', 'GH', '["en"]', 'GHS', '["AU","ECOWAS"]', 'GSE'),
('GIN', 'Guinea', 'GN', '["fr"]', 'GNF', '["AU","ECOWAS"]', NULL),
('GNB', 'Guinea-Bissau', 'GW', '["pt"]', 'XOF', '["AU","ECOWAS"]', NULL),
('KEN', 'Kenya', 'KE', '["en","sw"]', 'KES', '["AU","EAC"]', 'NSE'),
('LSO', 'Lesotho', 'LS', '["en","st"]', 'LSL', '["AU","SADC"]', NULL),
('LBR', 'Liberia', 'LR', '["en"]', 'LRD', '["AU","ECOWAS"]', NULL),
('LBY', 'Libya', 'LY', '["ar"]', 'LYD', '["AU"]', 'LSM'),
('MDG', 'Madagascar', 'MG', '["fr","mg"]', 'MGA', '["AU","SADC"]', NULL),
('MWI', 'Malawi', 'MW', '["en"]', 'MWK', '["AU","SADC"]', 'MSE'),
('MLI', 'Mali', 'ML', '["fr"]', 'XOF', '["AU","ECOWAS"]', 'BRVM'),
('MRT', 'Mauritania', 'MR', '["ar"]', 'MRU', '["AU"]', NULL),
('MUS', 'Mauritius', 'MU', '["en"]', 'MUR', '["AU","SADC"]', 'SEM'),
('MAR', 'Morocco', 'MA', '["ar","fr"]', 'MAD', '["AU"]', 'CSE'),
('MOZ', 'Mozambique', 'MZ', '["pt"]', 'MZN', '["AU","SADC"]', 'BVM'),
('NAM', 'Namibia', 'NA', '["en"]', 'NAD', '["AU","SADC"]', 'NSX'),
('NER', 'Niger', 'NE', '["fr"]', 'XOF', '["AU","ECOWAS"]', 'BRVM'),
('NGA', 'Nigeria', 'NG', '["en"]', 'NGN', '["AU","ECOWAS"]', 'NGX'),
('RWA', 'Rwanda', 'RW', '["en","fr","rw"]', 'RWF', '["AU","EAC"]', 'RSE'),
('STP', 'São Tomé and Príncipe', 'ST', '["pt"]', 'STN', '["AU"]', NULL),
('SEN', 'Senegal', 'SN', '["fr"]', 'XOF', '["AU","ECOWAS"]', 'BRVM'),
('SYC', 'Seychelles', 'SC', '["en","fr"]', 'SCR', '["AU","SADC"]', 'MERJ'),
('SLE', 'Sierra Leone', 'SL', '["en"]', 'SLE', '["AU","ECOWAS"]', NULL),
('SOM', 'Somalia', 'SO', '["so","ar"]', 'SOS', '["AU"]', NULL),
('ZAF', 'South Africa', 'ZA', '["en","af","zu"]', 'ZAR', '["AU","SADC"]', 'JSE'),
('SSD', 'South Sudan', 'SS', '["en"]', 'SSP', '["AU","EAC"]', NULL),
('SDN', 'Sudan', 'SD', '["ar","en"]', 'SDG', '["AU"]', 'KSE'),
('SWZ', 'Eswatini', 'SZ', '["en","ss"]', 'SZL', '["AU","SADC"]', 'ESE'),
('TZA', 'Tanzania', 'TZ', '["sw","en"]', 'TZS', '["AU","EAC","SADC"]', 'DSE'),
('TGO', 'Togo', 'TG', '["fr"]', 'XOF', '["AU","ECOWAS"]', 'BRVM'),
('TUN', 'Tunisia', 'TN', '["ar","fr"]', 'TND', '["AU"]', 'BVMT'),
('UGA', 'Uganda', 'UG', '["en","sw"]', 'UGX', '["AU","EAC"]', 'USE'),
('ZMB', 'Zambia', 'ZM', '["en"]', 'ZMW', '["AU","SADC"]', 'LuSE'),
('ZWE', 'Zimbabwe', 'ZW', '["en","sn","nd"]', 'ZWL', '["AU","SADC"]', 'ZSE')
ON CONFLICT (country_code) DO NOTHING;

-- Seed Nigeria's regulatory framework as example
INSERT INTO public.regulatory_frameworks (country_code, name, category, regulator_name, mandatory, applicable_entity_types, reporting_frequency, enforcement_risk) VALUES
('NGA', 'NGX ESG Disclosure Guidelines', 'esg', 'Nigerian Exchange Group', true, '["legal_entity"]', 'annual', 'high'),
('NGA', 'CBN Climate Risk Disclosure', 'climate', 'Central Bank of Nigeria', true, '["legal_entity"]', 'annual', 'high'),
('NGA', 'NESREA Environmental Standards', 'esg', 'NESREA', true, '["legal_entity"]', 'annual', 'medium'),
('KEN', 'NSE ESG Disclosure Guidance', 'esg', 'Nairobi Securities Exchange', false, '["legal_entity"]', 'annual', 'medium'),
('ZAF', 'JSE Sustainability Disclosure', 'esg', 'Johannesburg Stock Exchange', true, '["legal_entity"]', 'annual', 'high'),
('ZAF', 'Carbon Tax Act', 'carbon', 'SARS', true, '["legal_entity"]', 'annual', 'high'),
('GHA', 'GSE Sustainability Reporting', 'esg', 'Ghana Stock Exchange', false, '["legal_entity"]', 'annual', 'low')
ON CONFLICT DO NOTHING;
