// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptfrzwsivtetvmdotfui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZnJ6d3NpdnRldHZtZG90ZnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTQ1MjAsImV4cCI6MjA2NTU3MDUyMH0.2IWT0RjoMao3zA7O2rmt5t9mHiRdsF0mPhbnHpnkLMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);